# Generated by Django 5.2 on 2025-04-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('New Appointment', 'New Appointment'), ('Appointment Cancelled', 'Appointment Cancelled'), ('Appointment Completed', 'Appointment Completed')], max_length=100),
        ),
    ]
